---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    kubernetes.io/metadata.name: tekton-pipelines
  name: tekton-pipelines
